name: Destroy Bootstrap Terraform backend

on:
  workflow_dispatch: 

jobs:
  destroy-state:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/bootstrap

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.TERRAFORMUSER_AWS_ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.TERRAFORMUSER_AWS_SECRET_ACCESSKEY}}
          aws-region: us-east-1

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      # Step 4: Initialize Terraform (without backend)
      - name: Terraform Init
        run: terraform init -backend=false

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 4: Terraform destroy (only on push to main)
      - name: Terraform Destroy
        run: terraform apply -destroy -auto-approve