name: Terraform Destroy

on:
  workflow_dispatch: 

jobs:
  destroy-state:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.TERRAFORMUSER_AWS_ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.TERRAFORMUSER_AWS_SECRET_ACCESSKEY}}
          aws-region: us-east-1

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      # Step 4: Destroy Infrastructure
      - name: Destroy Infrastructure
        run: |
          # Initialize Terraform for infrastructure
          terraform init
          terraform plan
          terraform apply -destroy -auto-approve
        working-directory: terraform/infrastructure

      # Step 5: Destroy Bootstrap Resources
      - name: Destroy Bootstrap Resources
        run: |
          # Initialize Terraform for bootstrap
          terraform init

          # Import remote resources
          terraform import aws_s3_bucket.state_bucket mytf-state-app-bucket
          terraform import aws_dynamodb_table.terraform_lock_table terraform-lock-table

          # Remove bucket state
          terraform state rm aws_s3_bucket.state_bucket
        working-directory: terraform/bootstrap

      # Step 6: Destroy AWS S3 bucket via AWS CLi
      - name: Destroy AWS S3 bucket via AWS CLi
        run: |
          aws s3api list-object-versions --bucket mytf-state-app-bucket --region us-east-1
          aws s3api delete-objects --bucket mytf-state-app-bucket --region us-east-1 --delete "$(aws s3api list-object-versions --bucket mytf-state-app-bucket --region us-east-1 --query='{Objects: Versions[].{Key:Key,VersionId:VersionId}}')"
          aws s3api delete-objects --bucket mytf-state-app-bucket --region us-east-1 --delete "$(aws s3api list-object-versions --bucket mytf-state-app-bucket --region us-east-1 --query='{Objects: DeleteMarkers[].{Key:Key,VersionId:VersionId}}')"
          aws s3 ls s3://mytf-state-app-bucket --region us-east-1
          aws s3api delete-bucket --bucket mytf-state-app-bucket --region us-east-1
        working-directory: terraform/bootstrap

      # Step 7: Destroy resource
      - name: Destroy resource
        run: |
          terraform plan
          terraform apply -destroy -auto-approve
        working-directory: terraform/bootstrap